### ISSUE TITLE
Anti-aliased lines and circles

### ISSUE THREAD

**Issue by xandark** [CruiserOne/Astrolog#10]
I am honestly amazed by the features of this free software after I have re-discovered it 20 years later. Yet the stair-stepped, jagged lines and non-smooth circles makes it hard on my eyes. It also makes it look behind the times.

I cannot have been the first person to request anti-aliasing. Is there a technical reason why it cannot or won't be implemented?

Regardless, thank you for all the other great parts.

**Comment by CruiserOne** [comment]
Astrolog is over 30 years old, so was developed using API from 30 years ago. On Windows Astrolog uses classic GDI, while on Unix flavors Astrolog uses X11 API, neither of which support anti-aliasing. A strict distinction between pixels that are part of the chart, and pixels that aren't, allow some unique features, such as raising up pixels that are part of the chart to produce a 3D overview of a chart, such as [seen in this video](https://www.youtube.com/watch?v=euxwoyekZow).

Astrolog does support vector graphics in various formats. For example, save the chart to PostScript file format, to Windows metafile format, or even just print it from Windows, and those lines will be anti-aliased on the screen or smooth when printed. Astrolog also supports several different system fonts, so [text and glyphs can be anti-aliased](https://i.imgur.com/op4SIkU.png) if one wants. You can also just increase the line thickness, which may look better on its own. Or combine increased line thickness with manually shrinking the dimensions of the chart in a bitmap editor to produce anti-aliasing yourself, such as [seen in this picture](https://i.imgur.com/TIt49IX.png).

**Comment by xandark** [comment]
Yes, I've noticed that the text and glyphs are anti-aliased and that the lines can be thickened, and I've seen the video, which reminded me of a retro pixel art experiment and less something of any use. And I'm aware that an extra export step can get vector images. But that's not what I'm looking for. I'm looking for software that is easy on my eyes for day-to-day use.

So I see that the issue is closed--are you opposed to any further ideas in this regard?

From 20 years ago, I remember that the old GDI drawing commands can be rastered into an offscreen bitmap, and if that's the case, then anti-aliased Bresenham lines could just as easily be substituted, and nothing big would have to change.

**Comment by CruiserOne** [comment]
No, I'm not opposed to this or related feedback, and thank you for your suggestions! :) Indeed, rendering thicker lines into a larger offscreen bitmap, and then copying that back to the screen while blending pixels together, is one way to fake anti-aliased lines, at least when using Windows GDI. Another option is to switch to OpenGL, DirectX, or some other drawing library, although that's a more major undertaking.

**Comment by xandark** [comment]
I didn't even think of that, yes, that's a simple solution while staying within the GDI API.

**Comment by CruiserOne** [comment]
Note that the newest Astrolog version 7.80 offers a simple form of anti-aliasing on the Windows screen, and when creating Windows bitmap files. In [this screenshot](https://www.astrolog.org/astrolog/pic/linetype.png), compare the non-antialiased chart pixels on the left, with the anti-aliased on the right in which the diagonal lines/circles might be considered to look better.

**Comment by xandark** [comment]
Thank you for considering even working on this, but my eyes cannot look at the new solution for more than a few seconds. It's just too painful for me to parse. Real antialiasing is a beautiful thing and very easy on the eyes.

Since you're drawing to a bitmap, why not substitute your line drawing functions for a hand-rolled one like:
https://www.geeksforgeeks.org/dsa/anti-aliased-line-xiaolin-wus-algorithm/

**Comment by CruiserOne** [comment]
Thank you for your feedback. :) The problem with classic anti-aliasing is that one pixel wide lines often produce poor results. For example, for a black line on a white background, a near horizontal line will half the time be a nice black line, and half the time be a 2 pixel wide gray line which looks bad. Astrolog's antialiasing can potentially be considered better because it uses a technique similar to [font hinting](https://en.wikipedia.org/wiki/Font_hinting), in which parts of lines snap to pixel boundaries, to increase edge contrast and ensure there are always black pixels everywhere along a line.

Anyway, the option described is now available, and users can turn it on or off as they prefer. I am of course continuing to evaluate and work with the program, and there may be other additions to this area in the future. :)

**Comment by xandark** [comment]
> The problem with classic anti-aliasing is that one pixel wide lines often produce poor results. For example, for a black line on a white background, a near horizontal line will half the time be a nice black line, and half the time be a 2 pixel wide gray line which looks bad.

The difference is that in a natal chart drawn with 100% anti-aliased lines on a floating-point coordinate system, the lines are not constrained to 1px width because of that very effect. They're 2px or 3px wide, which on today's monitors is still nothing. Maybe back in 1996 jumping from 1px to 2px for a line width was a substantial visual difference, but today it is nothing. 

> Note that the newest Astrolog version 7.80 offers a simple form of anti-aliasing on the Windows screen, and when creating Windows bitmap files. In [this screenshot](https://www.astrolog.org/astrolog/pic/linetype.png), compare the non-antialiased chart pixels on the left, with the anti-aliased on the right in which the diagonal lines/circles might be considered to look better.

But these lines are still not "anti-aliased" and to call it that is a misnomer.  It's something else. Maybe "fattened aliased lines" is more apropos.

We can all see that there is a stair-stepping on all the lines. And the coordinates for all the lines are not floating point, but integer and every line must start or end exactly in the center of a pixel. That doesn't help either.

>  I am of course continuing to evaluate and work with the program, and there may be other additions to this area in the future. :)

I hope so. It's such a powerful program but the aliasing and snapping of every endpoint to a integer grid makes it look amateur. Sorry to say that, but that's my honest opinion.
