### ISSUE TITLE
Astrolog for Linux or Web Browser?

### ISSUE THREAD

**Issue by zohozer** [CruiserOne/Astrolog#19]
HI. I do like this software but recently I switched to Linux and this is one of the softwares for which I can't find any replacement.

It is possible to see a full version of Astrolog software build for Linux and / or Web Browser?

**Comment by zvezdochiot** [comment]
Hi @zohozer .

Type (in console):
```shell
make
```
Type:
```
./astrolog
```

Good luck.

**Comment by toddcarnes** [comment]
You can get the Linux and macOS versions of astrolog at https://codeberg.org/toddcarnes/Astrolog-64/releases/tag/v7.60

**Comment by CruiserOne** [comment]
As others have indicated, Astrolog can be compiled for Linux, using the Unix file "Makefile" that comes with the source code here. There are also precompiled Linux binaries for Astrolog available at external sites (see above).

Astrolog for Linux has windowed graphics (if compiled with X11) which can be interacted with using keypresses and the mouse. However, the X11 version of Astrolog does not at this time offer a full Graphical User Interface (GUI) with menus and dialogs, like the MS Windows version has.

Similarly, there is no Web browser version of Astrolog at this time either, although there are Web sites which call Astrolog behind the scenes to generate charts, and present the results in your browser, such as the "Pullen/Astro" tab on Astro.com: http://www.astro.com/cgi/genchart.cgi?&lang=e&gm=pu

**Comment by Yaksinikos** [comment]
> HI. I do like this software but recently I switched to Linux and this is one of the softwares for which I can't find any replacement.
> 
> It is possible to see a full version of Astrolog software build for Linux and / or Web Browser?

Actually the X11 version is kind of hard to use, but if you like, you can always use the windows version trough bottles - works flawless, am using it now for months.
