### ISSUE TITLE
Question on midpoints and aspects 

### ISSUE THREAD

**Issue by tbikeev** [CruiserOne/Astrolog#24]
Hello @CruiserOne!

A question on the aspects between midpoints `-ma` 

> -ma: Like -m but show aspects from midpoints to planets as well.

Can I show:
1. aspects from planets in chart1 to midpoints in chart2?
2. aspects from midpoints in chart1 to midpoints in chart2?

`-ma` seems to affect only one chart, it seems.

Cheers, Thomas

**Comment by CruiserOne** [comment]
The -ma switch feature indeed only works within one chart, and shows aspects between planets and midpoints in that chart. It does not show midpoints between planets and midpoints in another chart, or aspects between midpoints of two different charts.

It is possible to define a custom object to be a particular midpoint (e.g. the Sun/Moon midpoint) which then gets treated the same as a planet and can be compared to other charts or other instances of that custom object. Use the -Fm switch to define an unused object slot to be a particular midpoint.
