### ISSUE TITLE
请问 有.net Core可以使用的dll吗? 我是初学者 请问能否发布一个用于.netCore的dll?

### ISSUE THREAD

**Issue by wangwwww** [CruiserOne/Astrolog#3]
请问 有.net Core可以使用的dll吗? 我是初学者 请问能否发布一个用于.netCore使用的dll? 谢谢

**Comment by CruiserOne** [comment]
Astrolog is an executable program, and not a Windows DLL. There is no DLL version of Astrolog at this time. Note that Astrolog does have a command line only version, and every feature and setting is accessible and changeable from the command line. That makes it easy to drive Astrolog from shell scripts or other programs, by simply composing appropriate command lines, so for some scenarios a DLL isn't necessary.

**Comment by wangwwww** [comment]
> Astrolog是一个可执行程序，而不是Windows DLL。目前没有DLL版本的Astrolog。请注意，Astrolog确实具有仅命令行版本，并且每个功能和设置都可以从命令行访问和更改。通过简单地编写适当的命令行，可以轻松地从Shell脚本或其他程序驱动Astrolog，因此在某些情况下不需要DLL。



> Astrolog是一个可执行程序，而不是Windows DLL。目前没有DLL版本的Astrolog。请注意，Astrolog确实具有仅命令行版本，并且每个功能和设置都可以从命令行访问和更改。通过简单地编写适当的命令行，可以轻松地从Shell脚本或其他程序驱动Astrolog，因此在某些情况下不需要DLL。

Thank you for your reply. I hope there will be a DLL that can be used for.netcore to integrate Astrolog. If there is no DLL, I will study it again
