### ISSUE TITLE
Compile on ubuntu 20.04.2 amd64

### ISSUE THREAD

**Issue by Raj52537** [CruiserOne/Astrolog#4]
I am able to compile the latest version as shared library 
It is running fine on terminal but how to enable graphical mode (compile as executable) 
Using latest gcc

**Comment by CruiserOne** [comment]
To compile in windowed graphics, uncomment the "#define X11" line near the top of astrolog.h before running make. Afterward, run with the -X command switch to bring up a window. See the compiler instructions in the documentation file for details: [http://www.astrolog.org/ftp/astrolog.htm#compile](http://www.astrolog.org/ftp/astrolog.htm#compile)

**Comment by Raj52537** [comment]
It's already uncommented.
I haven't changed anything.
But it is compiling as shared library (cannot launch with double click) 
I am even able to run it from cli with ./astrolog command
with -X command switch it is showing window and I am able to use this.
Thanks for great program and quick help.

**Comment by toddcarnes** [comment]
It is **NOT** compiling as a "shared library". It is compiling as executable. There is no GUI in the linux version of astrolog. It only runs in a terminal. The Windows version is the only version with a GUI.

**Comment by Raj52537** [comment]
Sir here is the output of file command

$ file ./astrolog
./astrolog: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=e15e9a7691a8c61a38aaa7db4e2b4bd48dba1526, for GNU/Linux 3.2.0, stripped

I have compiled version 6.3 at that time on linux (slax 7) and it runs with double click.

Btw no problem I can go with windows version via wine then.

**Comment by CruiserOne** [comment]
Indeed, Astrolog on Linux is a command line executable. The -X command switch will pop up a graphics window, and one can interact with that window some with the mouse and keyboard, but it's not a full GUI. The Windows command line version works similarly, and can also create a window with the -X switch. (That's different from the Windows full GUI version, which also has menus and dialogs and all, and which you do launch by double clicking its icon.)

**Comment by Raj52537** [comment]
That might be changed in current version
Here find the version 6.3 I have compiled at that time
It an be opened with double click
https://github.com/Raj52537/Temp
