### ISSUE TITLE
astrolog -Xi -Xn -XG crash on Mageia 8

### ISSUE THREAD

**Issue by katnatek** [CruiserOne/Astrolog#5]
I try to make a rpm package of astrolog7.20 for Mageia 8, the build goes fine so i install the rpm and try to run.

 i try the astrolog -Xi -Xn -XG command suggested on your site, it try to show something but fail
[strace-mageia8.txt](https://github.com/CruiserOne/Astrolog/files/6720935/strace-mageia8.txt)

**Comment by CruiserOne** [comment]
Assuming you've compiled in X11 Window graphics (which Mageia Linux should be running) do this command instead (i.e. append ":Xbb" to the command line): astrolog -Xi -Xn -XG :Xbb

The new 24 bit bitmaps introduced in version 7.20 can't be drawn within an X11 window, which is still limited to the 16 color palette of previous versions. That limitation is known and not a bug, however what is a bug is that Astrolog shouldn't crash if you try, and should fall back to the old format automatically. The -XG switch will by default attempt to draw a detailed globe, so we need to turn that detail off. Change line 166 in your astrolog.as default settings file from ":Xbw" to ":Xbb", and detailed bitmaps will be off by default, and "astrolog -Xi -Xn -XG" by itself should work.

You can at least create detailed bitmap files on all systems. For example you can get an image like http://www.astrolog.org/astrolog/screen/astgraf2.png with the command line: astrolog -n -XG -Xo file.bmp

**Comment by katnatek** [comment]
> Assuming you've compiled in X11 Window graphics (which Mageia Linux should be running) do this command instead (i.e. append ":Xbb" to the command line): astrolog -Xi -Xn -XG :Xbb
> 
That works, thank you

> The new 24 bit bitmaps introduced in version 7.20 can't be drawn within an X11 window, which is still limited to the 16 color palette of previous versions. That limitation is known and not a bug, however what is a bug is that Astrolog shouldn't crash if you try, and should fall back to the old format automatically. The -XG switch will by default attempt to draw a detailed globe, so we need to turn that detail off. Change line 166 in your astrolog.as default settings file from ":Xbw" to ":Xbb", and detailed bitmaps will be off by default, and "astrolog -Xi -Xn -XG" by itself should work.
> 
I will try to integrate that on the package so the users don't have to do ;) 

I will comment as soon as i make the test with new package

**Comment by katnatek** [comment]
Ok changing line 155 of astrolog.as at build time make once installed the package the command  "astrolog -Xi -Xn -XG" run without issues.

I hope other things also.
