### ISSUE TITLE
unknown switch -Ya0

### ISSUE THREAD

**Issue by Yaksinikos** [CruiserOne/Astrolog#7]
Just downloaded the new version, tried to run it.
v. 740

it returns me a message;
`Astrolog: Unknown switch '-Ya0'`

Downloaded the cli version, run on Linux.

**Comment by CruiserOne** [comment]
There's a "-Ya0" command switch in the astrolog.as default settings file that comes with version 7.40, which is automatically loaded and applied when the program starts. The "-Ya0" switch was added in version 7.40, which means it doesn't exist in previous versions. In other words, this error will happen if an old version of Astrolog tries to load the version 7.40 astrolog.as file.

Do you by chance have any older versions of Astrolog on your system? For example, if your path has "astrolog" run from some other location before the current path, and you type "astrolog" in the version 7.40 directory, that could potentially cause it.

As an alternative, edit your astrolog.as file and just delete like 37 which starts with "-Ya0". That should allow Astrolog to load the file without error, and you can see in the subsequently displayed chart whether it's actually the new version 7.40 running.

**Comment by Yaksinikos** [comment]
> Do you by chance have any older versions of Astrolog on your system? For example, if your path has "astrolog" run from some other location before the current path, and you type "astrolog" in the version 7.40 directory, that could potentially cause it.

Actually yes, did just run the old version with new config :D sorry.
astrolog is installed on my system trough AUR
