### ISSUE TITLE
suggestion: How about rewrite it using the wxWidgets framework

### ISSUE THREAD

**Issue by dukeware** [CruiserOne/Astrolog#8]
This is an excellent astrology software. Once again, I salute the authors. How about rewrite it using the wxWidgets[1] GUI framework? So that all platforms, especially non Windows systems, can fully run and use it. 

[1] https://github.com/wxWidgets/wxWidgets

**Comment by zvezdochiot** [comment]
Do it. ;)

See also: https://github.com/martin-pe/maitreya8

**Comment by dukeware** [comment]
@zvezdochiot thanks

**Comment by CruiserOne** [comment]
Thank you for the pointer, I'll look into it! :) Indeed, outside of its Windows-only GUI version, Astrolog is a command line executable. The command line version has access to every text and graphics chart and setting as the Windows version, but it requires using the command line interface. If the X11 graphics option is compiled in, then Astrolog's -X command switch will pop up a graphics window, and one can interact with that window some with the mouse and keyboard. That does at least allow graphics on Linux and Mac, however that's still not a full GUI with menus and dialogs and all.
